spring:
 application:
  name:
   auth-service

 profiles:
   active: ${SPRING_PROFILES_ACTIVE:dev} # default to dev

  # --- Database ---------------------------------------------
 datasource:
  url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3308}/${DB_NAME:auth_service_db}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
  username: ${DB_USERNAME}
  password: ${DB_ROOT_PASSWORD}
  driver-class-name: com.mysql.cj.jdbc.Driver

  # ---- JPA -----------------------------------
 jpa:
   hibernate:
    ddl-auto: validate            # Flyway manages schema, hibernates only validates
   show-sql: false
   properties:
     hibernate:
       dialect: org.hibernate.dialect.MySQL8Dialect
       format_sql: true

 # 1. Flyway manages schema, hibernates only validates
 flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: true

 # Redis
 data:
   redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD}

 # Mail
 mail:
   host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
   port: ${MAIL_PORT:2525}
   username: ${MAIL_USERNAME}
   password: ${MAIL_PASSWORD}
   properties:
    mail:
     smtp:
      auth: true
      starttls:
       enable: true

# OAuth2
 security:
   oauth2:
     client:
       registration:
         github:
           client-id: ${GITHUB_CLIENT_ID}
           client-secret: ${GITHUB_CLIENT_SECRET}
           scope:
             - read:user
             - user:email
           redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

#         google:
#           client-id: ${GOOGLE_CLIENT_ID}
#           client-secret: ${GOOGLE_CLIENT_SECRET}
#           scope:
#             - openid
#             - email
#             - profile
#           redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}""

  # App Custom Properties
app:
  frontend-url: ${FRONTEND_URL:*}
  jwt:
   secret: ${JWT_SECRET}
   access-token-expiry: 900000 # 15 minutes in milliseconds
   refresh-token-expiry: 604800000

 # Server
server:
 port: 8080
 error:
  include-message: always
  include-binding-errors: always

# Logging
logging:
 level:
   com.brijesh: DEBUG
   org.springframework.security: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: when_authorized  # prod: hide details from public