spring:
  application:
    name: email-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # Kafka Consumer Config
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: email-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.brijesh.emailservice.event.BaseEvent


  # Mail
  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:2525}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8082

#  Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}


app:
  auth-service-url: ${AUTH_SERVICE_URL:http://localhost:8081}


# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    com.brijesh.emailservice: DEBUG
    org.springframework.kafka: INFO